apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-function-template.fullname" .}}-configmap
data:
  env: {{ .Values.environment }}
  region: {{ .Values.region | default "us-east-1" | quote | trim  | lower }}
  passsword: {{ randAlphaNum 10 | quote }}
  secret: {{ b64enc "ram@123@" | quote }}
  time: {{ now | quote }}
  image: {{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}
  replicas: {{ .Values.replicas | default 1 }}
  labels: |
{{ toYaml .Values.labels | indent 4}}


